<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-10-16 06:20
=======
# Generated by Django 4.0.6 on 2022-08-22 01:53
>>>>>>> b1c4beba0de6bf9a5f13a7bf134bb4c8e3f951df

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 6, 20, 16, 808441)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 1, 53, 21, 656450)),
>>>>>>> b1c4beba0de6bf9a5f13a7bf134bb4c8e3f951df
        ),
    ]
